/* Generated by Together */

#ifndef MESHDATA_H
#define MESHDATA_H

#include <vector>

#include "elemento_2d.hpp"
#include "levpoint.h"

/**
 * @stereotype struct 
 */
class meshData
{
public:    
    std::vector<CLevPoint> vPoints;
    std::vector<Elemento_2D> vElements;
};
#endif //MESHDATA_H