/* Generated by Together */

#include "simplexy.h"

void CSimpleXY::X(double xi)
{
	x = xi;
}
void CSimpleXY::Y(double yi)
{
	y = yi;
}

double CSimpleXY::X(void){ return x;}
double CSimpleXY::Y(void){ return y;}
